version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
