version: "3.8"

services:
  database:
    image: postgres:16
    container_name: synthra-database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    image: delemangi/synthra-backend:latest
    container_name: synthra-backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    image: delemangi/synthra-frontend:latest
    container_name: synthra-frontend
    restart: unless-stopped
    ports:
      - "80:5000"
