name: synthra-dev

services:
  database:
    image: postgres:16
    container_name: synthra-database-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: delemangi/synthra-backend:latest
    container_name: synthra-backend-dev
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./assets:/assets
    ports:
      - "8002:8002"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    image: delemangi/synthra-frontend:latest
    container_name: synthra-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: synthra-pgadmin-dev
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
