name: synthra

services:
  database:
    image: postgres:16
    container_name: synthra-database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    image: delemangi/synthra-backend:latest
    container_name: synthra-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./assets:/app/assets
    env_file:
      - .env

  frontend:
    image: delemangi/synthra-frontend:latest
    container_name: synthra-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
