version: "3.8"

services:
  database:
    image: postgres:16
    container_name: synthra-database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synthra-backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "81:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synthra-frontend
    restart: unless-stopped
    ports:
      - "80:5000"
