version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  # FastAPI Backend
  fastapi-backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "80:80"
    networks:
      - mynetwork

  # Svelte Frontend
  svelte-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pg_data:
