name: synthra-dev

services:
  database:
    image: postgres:16
    container_name: synthra-database-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: delemangi/synthra-backend:latest
    container_name: synthra-backend-dev
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8002:8002"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: delemangi/synthra-frontend:latest
    container_name: synthra-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
