version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/synthra
    command: sleep infinity
    network_mode: service:database

  database:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - 8001:80
