"""Add 2FA auth

Revision ID: 0f18e18f9ae9
Revises: adbfe149f408
Create Date: 2024-06-11 00:00:10.056063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f18e18f9ae9'
down_revision: Union[str, None] = 'adbfe149f408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('code_2fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'code_2fa')
    # ### end Alembic commands ###
