"""Create share

Revision ID: 956387bf4a93
Revises: a635e77b2a18
Create Date: 2024-06-07 22:52:36.290988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956387bf4a93'
down_revision: Union[str, None] = 'a635e77b2a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('shared', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'shared')
    # ### end Alembic commands ###
