"""Delete shares when files are deleted

Revision ID: 9fc938c05584
Revises: 548cdd92ed41
Create Date: 2024-06-16 21:24:22.326404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc938c05584'
down_revision: Union[str, None] = '548cdd92ed41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shares_file_id_fkey', 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key('shares_file_id_fkey', 'shares', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
