name: Lint Backend

on:
  pull_request:
    paths:
      - "backend/**"

jobs:
  lint_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          cd backend
          poetry install

      - name: Ruff Lint Backend
        run: |
          cd backend
          poetry run ruff check .
